name: video_thumbnail_platform_interface
description: A common platform interface for the video_thumbnail plugin.
repository: https://github.com/earGO/video_thumbnail_plugin/tree/master/packages/video_thumbnail_platform_interface
issue_tracker: https://github.com/earGO/video_thumbnail_plugin/issues
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 2.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0